# Generated by Django 3.2.7 on 2022-01-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0005_auto_20220116_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
