# Generated by Django 3.2.7 on 2022-01-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_meetmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetModel',
            new_name='Meet',
        ),
    ]
