# Generated by Django 3.2.7 on 2022-01-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_meetmodel_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='meeting_link',
            field=models.URLField(default=-1.0),
            preserve_default=False,
        ),
    ]
